# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Acute Angular
email: i@krishnanmk.com
description: > # this means to ignore newlines until "baseurl:"
  An Angular blog focusing on the minute issues first
baseurl: "/acute-angular" # the subpath of your site, e.g. /blog
url: "http://kichnan.github.io" # the base hostname & protocol for your site, e.g. http://example.com
port: 4003
twitter_username: kichnan
github_username:  kichnan

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Other settings
exclude: [
  /assets/node_modules
]

# Other settings that may be of use in future
# include, exclude, show_drafts 
# defaults (for YAML Front Matter)

# Some useful build command options
# JEKYLL_ENV=production/development
